version: '3.3'

services:
    web:
        build:
            context: ./
            dockerfile: Dockerfile
        # Открываем порт 8000 наружу
        expose:
            - 8000
        # Подключаем статические и медиа файлы
        volumes:
            - .:/maria_bublyk_bot
        env_file:
            - .envs/.env.prod
        # Дожидаемся запуска db
        depends_on:
            - db

    db:
        image: postgres:12.0-alpine
        build:
            context: ./docker/postgres
            dockerfile: Dockerfile
        env_file:
            - .envs/.env.prod.db

    nginx:
        build:
            context: ./docker/nginx
            dockerfile: Dockerfile
        depends_on:
            - web
            - db
        ports:
            - "8000:80"

    redis:
        image: "redis"
        restart: always
        command: redis-server
        ports:
            - '6379:6379'

    celery:
        build: .
        command: celery worker -A tasks -l info -B
        volumes:
            - .:/maria_bublyk
        env_file:
            - .envs/.env.prod
        depends_on:
            - db
            - redis
