version: '3.3'

services:
    web:
        build:
            context: ./
            dockerfile: Dockerfile
        # Открываем порт 8000 наружу
        expose:
            - 8000
        # Подключаем статические и медиа файлы
        volumes:
            - .:/app
        env_file:
            - .envs/.env.prod
        # Дожидаемся запуска db
        depends_on:
            - db

    db:
        image: postgres:latest
        build:
            context: ./docker/postgres
            dockerfile: Dockerfile
        ports:
            - 5432:5432
        volumes:
            - ./data/db:/var/lib/postgresql/data
        env_file:
            - .envs/.env.prod.db

    nginx:
        build:
            context: ./docker/nginx
            dockerfile: Dockerfile
        depends_on:
            - web
            - db
        ports:
            - 8000:80

    redis:
        image: redis:alpine
        restart: always
        command: redis-server
        ports:
            - 6379:6379

#    celery:
#        build:
#            context: .
#        restart: always
#        command: celery worker -A tasks -l info -B
#        volumes:
#            - .:/app
#        env_file:
#            - .envs/.env.prod
#        links:
#            - redis
#        depends_on:
#            - db
#            - redis

volumes:
  database-data: